// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJLrlsFC6y2qj34mFuxPNFgI1zDkMLg7A',
    appId: '1:836627886254:web:4e4ec0c09efaefd5b0bd3f',
    messagingSenderId: '836627886254',
    projectId: 'velocity-ark-project',
    authDomain: 'velocity-ark-project.firebaseapp.com',
    databaseURL: 'https://velocity-ark-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velocity-ark-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHtGPE1Oihs4pf2q4W2fvqZVppco5XZxc',
    appId: '1:836627886254:android:96add0f1084e36adb0bd3f',
    messagingSenderId: '836627886254',
    projectId: 'velocity-ark-project',
    databaseURL: 'https://velocity-ark-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velocity-ark-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQOZAe_USlkPpJsmM-VJLqq05ex2MsQk',
    appId: '1:836627886254:ios:ed433deba69e91a2b0bd3f',
    messagingSenderId: '836627886254',
    projectId: 'velocity-ark-project',
    databaseURL: 'https://velocity-ark-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velocity-ark-project.appspot.com',
    iosClientId: '836627886254-kbcvv0l80fs8i6nlpjtv2qa8445tjap3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobafluttertiga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQQOZAe_USlkPpJsmM-VJLqq05ex2MsQk',
    appId: '1:836627886254:ios:ed433deba69e91a2b0bd3f',
    messagingSenderId: '836627886254',
    projectId: 'velocity-ark-project',
    databaseURL: 'https://velocity-ark-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velocity-ark-project.appspot.com',
    iosClientId: '836627886254-kbcvv0l80fs8i6nlpjtv2qa8445tjap3.apps.googleusercontent.com',
    iosBundleId: 'com.example.cobafluttertiga',
  );
}
